base_path: /home/svein/mywiki
blurb_max: 50
date_format: '%Y-%m-%d'
home_page: index
markdown_exts:
- codehilite
- toc
- pykwiki.ext.tpl
- pykwiki.ext.post
postlist:
  max_pages: 5
  order_field: mtime
  order_type: descending
  per_page: 2
  post_type: preview
rss_max_entries: 20
site:
  author: Jules RANDOLPH
  base_url: 'posts.html'
  description: My personnal wiki
  keywords: example, pykwiki
  title: My personnal wiki
source_ext: .md
theme:slate
time_format: '%H:%M:%S'
timestamp_format: '%Y-%m-%d %H:%M'
web_prefix: ''
